### PR TITLE
MAINT: numpy dev docs have external link, add comment, cleanup

### PR DESCRIPTION
**Pull request by mattip**
continuation of numpy/numpy#10844

Also added a comment how to add new releases, and fixed a dangling ``<span>`` or two

Edit: formatting

### CODE REVIEW

**Comment by scopatz** [comment]
Looks like this has a conflict now

**Comment by mattip** [comment]
fixed

**Comment by scopatz** [comment]
Thanks @mattip!

**Comment by mattip** [comment]
Thanks for merging. Any idea when this goes live? I am still seeing the [old page](https://docs.scipy.org/doc/)

**Comment by scopatz** [comment]
No idea.  probably should be using something like [doctr](https://drdoctr.github.io/doctr/) here

**Comment by pv** [comment]
Hi, please don't merge PRs to this repository if you cannot update the
result (this is not automated).

**Comment by scopatz** [comment]
Hi @pv - happy to build and push up the docs.  I just looked for instructions and couldn't find any, other than `make html`.  How would I upload the docs once they are built?

**Comment by rgommers** [comment]
This requires SSH access to an Enthought-owned server that runs docs.scipy.org. I'll push it up tonight.

**Comment by scopatz** [comment]
Thanks @rgommers!

**Pull request merged**
