### PR TITLE
Add SciPy 1.13.0

### PR DESCRIPTION
**Pull request by tylerjereddy**
I just did `make dist` and `make upload` steps. I circumvented https://github.com/scipy/scipy/issues/20379 by using Python `3.11` instead of `3.9` in my base env, after completing the rest of the rel process.

### CODE REVIEW

**Review by rgommers — APPROVED** [review]
Thanks Tyler. Let's give this a go - I think the banner only updates once this is merged (if not, that needs a fix because it still says that 1.13.0 is unstable)

**Comment by rgommers** [comment]
Nope, that wasn't it - this step was missed: http://scipy.github.io/devdocs/dev/core-dev/index.html#updating-the-version-switcher. Do you want to handle this @tylerjereddy? I guess next time this should be done as soon as the release branch is created.

**Comment by tylerjereddy** [comment]
you mean reupload the docs with the preferred version change? I guess I'm getting confused per https://github.com/scipy/scipy/pull/20380

**Comment by tupui** [comment]
No need for a re-upload of the doc. We just need to get your PR for the version switcher in and the banner will work. The doc is pulling the yaml file from main.

(From https://scipy.github.io/devdocs/_static/version_switcher.json, which is main)

**Pull request merged**
