### PR TITLE
Add SciPy 1.9.1

### PR DESCRIPTION
**Pull request by tylerjereddy**
Add SciPy `1.9.1`

### CODE REVIEW

**Review by rgommers — APPROVED** [review]
Thanks Tyler

**Comment by rgommers** [comment]
I deployed it. Looks like there's still a thing with the version switcher, where `1.9.0` is marked as stable and `1.9.1` is red. @tupui can you please remind us what should be done about that?

**Comment by tupui** [comment]
The version switcher config file needs to be updated: https://github.com/scipy/scipy/blob/main/doc/source/_static/version_switcher.json (and we should probably update the release doc then).

I can make a PR on Monday if not done before that. I am away this WE.

**Comment by tupui** [comment]
I did this in https://github.com/scipy/scipy/pull/16922

**Comment by rgommers** [comment]
thanks!

**Pull request merged**
