### PR TITLE
Add SciPy 1.5.1

### PR DESCRIPTION
**Pull request by tylerjereddy**
Add SciPy 1.5.1

Just did `make dist` and `make upload` steps.

### CODE REVIEW

**Comment by rgommers** [comment]
Before deploying this PR, we get the warning box. I think after deploying it the new version will be picked up - let's give that a try.

image

**Comment by rgommers** [comment]
Hmm, this should be taken care of by these lines in `conf.py`:
```
scipy_versions = set(re.findall('scipy-([0-9.]{3,})', index_text))
scipy_latest_version = str(max(pkg_resources.parse_version(x) for x in scipy_versions))
```
plus the use of `SCIPY_LATEST_VERSION` in the `.js` snippet.

@pv what am I missing?

**Comment by pv** [comment]
Force reload page.

**Comment by rgommers** [comment]
> Force reload page.

indeed, sorry for the noise. given that it was the first time I had opened that page, I failed to think of that (but of course the javascript snippet needed reloading)

**Pull request merged**
