### PR TITLE
DOC: add scipy 0.18.0 links

### PR DESCRIPTION
**Pull request by ev-br**

### CODE REVIEW

**Comment by rgommers** [comment]
@ev-br would you mind uploading this? My desktop is in a box right now....

**Comment by ev-br** [comment]
The docs themselves were uploaded at the release time, but I forgot to update the front page. Done now, thanks for the reminder!
(And I'm adding this to the release checklist)

**Comment by pv** [comment]
Note that this page is missing link to the release notes:
https://docs.scipy.org/doc/scipy-0.18.0/reference/release.html

**Comment by ev-br** [comment]
Grrr. Can you please point me to where the source of that page is?

**Comment by pv** [comment]
scipy/doc/source/release.rst

**Comment by ev-br** [comment]
Thanks Pauli.
Here's the pull request https://github.com/scipy/scipy/pull/6455. I'm going to update and upload the docs in one go for 0.18.1.

**Comment by pv** [comment]
I went and edited the file manually to add the link: http://docs.scipy.org/doc/scipy-0.18.0/reference/release.html

**Comment by ev-br** [comment]
Thanks Pauli!

**Pull request merged**
