### PR TITLE
Fix links to SciPy 1.8.0/1.8.1 docs

### PR DESCRIPTION
**Pull request by rgommers**
Follow-up to gh-63

### CODE REVIEW

**Comment by rgommers** [comment]
Let me try to see if this actually fixes it. I'll run `make upload`, and if it doesn't work I'll revert that. It's already broken right now, so if this doesn't fix it then I think it's the `.htaccess` rule changes that went wrong @tylerjereddy.

**Comment by rgommers** [comment]
Nope, that didn't help. The `.htaccess` file looks like this now:
```
Options +SymLinksIfOwnerMatch
RewriteEngine On

RewriteRule ^numpy(/.*) https://numpy.org/doc/stable$1 [R=permanent,L]

Redirect 301 /doc/scipy/reference/objects.inv /doc/scipy/objects.inv

RewriteRule ^scipy/scipy-html.zip /doc/scipy-1.8.1/scipy-html-1.8.1.zip [L]
RewriteRule ^scipy/scipy-ref.pdf  /doc/scipy-1.8.1/scipy-ref-1.8.1.pdf  [L]
RewriteRule ^scipy/(.*) /doc/scipy-1.8.1/html-scipyorg/$1 [NC,L]
```

It seems inconsistent that `1.8.0` is missing but `1.8.1` is present.

**Comment by rgommers** [comment]
With current main, I see:

image


While with the changes in this PR, I see (blank page, but no 404):

image

**Comment by rgommers** [comment]
The issue is that `scipy-1.8.1/index.html` is empty, while `scipy-1.8.1/html-scipyorg/index.html` is what we want. I have a vague memory of this problem; it looks like an upload error because we do _not_ want `html-scipyorg` to exist in the URLs.

**Comment by rgommers** [comment]
Manually adding `html-scipyorg` to the URL fixes things: https://docs.scipy.org/doc/scipy-1.8.1/html-scipyorg/

I think the `Makefile` in the main scipy repo needs fixing here, this bit of the `upload` command seems wrong:
```
	cp -r build/html-scipyorg build/dist
	touch build/dist/index.html
```

**Comment by rgommers** [comment]
This is https://github.com/scipy/scipy/issues/14267#issuecomment-1034196161

**Comment by rgommers** [comment]
I'll try this for `1.8.1`:
```diff
diff --git a/doc/Makefile b/doc/Makefile
index fe93e87e7..bdf2102b7 100644
--- a/doc/Makefile
+++ b/doc/Makefile
@@ -89,8 +89,7 @@ doc-dist: html-scipyorg html
        -test -d build/htmlhelp || make htmlhelp-build
        -rm -rf build/dist
        mkdir -p build/dist
-       cp -r build/html-scipyorg build/dist
-       touch build/dist/index.html
+       cp -r build/html-scipyorg/* build/dist
        (cd build/html && zip -9qr ../dist/scipy-html.zip .)
        cp build/latex/scipy-ref.pdf build/dist
        chmod ug=rwX,o=rX -R build/dist
```

**Comment by rgommers** [comment]
The redirect rule currently says:
```
Redirect 301 /doc/scipy/reference/objects.inv /doc/scipy/objects.inv
```
And we do want `intersphinx` links to point to `https://docs.scipy.org/doc/scipy`. I think that's yet again broken right now, because we only have `scipy/html-scipyorg/objects.inv` (it got deleted by the upload, my manual fix on the server for `1.8.0` disappeared). So I'm going to upload new html docs for `1.8.1` and see if that fixes things.

**Comment by tylerjereddy** [comment]
Thanks, hopefully this process becomes sane at some point.

**Comment by rgommers** [comment]
Okay, `scipy` and `scipy-1.8.1` are fixed. Need to rebuild `1.8.0` too.

**Comment by rgommers** [comment]
Everything looks good now. This PR is deployed, things should work, and the `.htaccess` file should no longer need updating as part of the release process; this is what it looks like now:
```
/srv/docs_scipy_org/doc$ cat .htaccess
Options +SymLinksIfOwnerMatch
RewriteEngine On

RewriteRule ^numpy(/.*) https://numpy.org/doc/stable$1 [R=permanent,L]

Redirect 301 /doc/scipy/reference/objects.inv /doc/scipy/objects.inv
```

**Pull request merged**
